---
title: "Figure 1E PCA"
author: "RAC"
date: "23/04/2020"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: inline
---
```{r setup, message = F, warning = F, tidy=T}
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(tibble)
theme_set(
  theme_bw()  )
library(extrafont)
loadfonts(quiet = T)
library(ggrepel)
library(corrplot)
getwd()
library(matrixStats)
`%!in%` = Negate(`%in%`)
library("FactoMineR")
library("factoextra")
```



#load data

Count files for PCA analysis were generated by intersecting bed files from the mapped reads of each tiCLIP sample with a bed file containing all TUs segmented into 10kb blocks i.e. each bed entry = 1 x 10kb segment of a TU
```{r, message = F, warning = F, tidy=T}
#counts of tiCLIP reads from genes which have been segmented into 10kb bins  
all10kbbinrRNA<-read.csv("../../data/xiCLIP_all.hg38HeLaSoren10kbins.NormTorRNAFactor.counts", header= F, sep ="\t")

colnames(all10kbbinrRNA)<-c("Sample","chr","start","end","ID","binNumber","strand","count")
anno10kb<-read.table("../../data/hg38_HeLa_Soren.10kbins.200409.bed", header= F, sep ="\t")
#10kb segments are labelled in ascending numbers in col 5
head(anno10kb, n=30)
#count file
head(all10kbbinrRNA)
```

#wrangle data functions 
```{r, message = F, warning = F, tidy=T}


wrangle_data <- function(df) {
  df %>%
    separate(Sample, into=c("Protein","Rep","Timepoint")) %>%
    filter(!(Protein == "CBP20" & Rep == "3")) %>%
    separate(ID, into = c("GeneID","bioType","TotalExonNumber", "size"), sep=":::") %>%
    mutate(geneType = case_when(
      TotalExonNumber > 1 ~ "multiExonic",
      TRUE ~ "monoExonic"
    )) %>%
    select(-c(chr, start,end, TotalExonNumber, size, strand)) %>%
    mutate(Timepoint = case_when(Timepoint == "PBSDRB" ~ "t0", TRUE ~ Timepoint )) %>%
    unite(Sample, c("Protein","Timepoint","Rep")) %>%
    unite(ID, c("GeneID","bioType","binNumber"), sep="|") %>%
    mutate(log2count = log2(count+1)) %>%
    select(Sample, ID, geneType,log2count) %>%
    separate(ID, into=c("ID", "biotype", "binNumber"), sep="\\|")
}

data<-wrangle_data(all10kbbinrRNA)


data2 <- data %>%
  filter(biotype != "histone_coding",
         biotype != "snRNA")
```


#Figure 1 E - PCA analysis for multi and mono exonic genes with RBM7, CBP20, CBP80 and ALYREF. 



```{r, fig.asp= 1, message = F, warning = F, tidy=T}

PCAPlot<-function(df_log2, GENESTRUCTURE= c("multiExonic","monoExonic")){
m_all<-
  df_log2 %>%
  filter(geneType == GENESTRUCTURE ) %>% 
  unite(ID_binN, c("ID","binNumber", "biotype","geneType"), sep = ":::") %>%
  spread(Sample, log2count) %>% 
  column_to_rownames(var = "ID_binN")
  

######
#chose rows with over 100 counts
m_all<-m_all[rowSums(m_all) > 100, ]
#apply variance to rows and remove nas
myvars <- apply(m_all,1, var,na.rm=TRUE)
#sort by largest variance, and choose top 2000 bins with most variance 
myvars <- sort(myvars,decreasing=TRUE)[1:2000]

#make df of high variance genes.
highVarGenes<-
  myvars %>%
    names() %>%
    as.data.frame() %>%
    separate(".", into=c("ID","binNumber", "bioType","geneType"), sep=":::") %>%
    select(-binNumber) %>%
    unique() %>%
    select(ID)

###
unique_genes<-
myvars %>%
  names() %>%
  as.data.frame() %>%
  separate(".", into=c("ID","binNumber", "biotype","geneType"), sep=":::") %>%
  select(-binNumber) %>%
  group_by(biotype)  %>%
  summarise(uniqueID = n_distinct(ID), 
            nonUnique = n()) %>%
    mutate(total_nonUnique=sum(nonUnique),
         total_unique=sum(uniqueID)) %>% 
  select(total_unique) %>% 
  unique() %>% 
  as.matrix()

#select genes based on criteria above

df_log2_highVarGenes<-df_log2 %>%
  filter(ID %in% highVarGenes$ID) %>%
  unite("ID", c("ID","binNumber", "biotype","geneType"), sep="|") 

#all together

df_log2_highVarGenes_T<-df_log2_highVarGenes %>%
    spread(ID, log2count) 
  
  row.names(df_log2_highVarGenes_T) <- paste(df_log2_highVarGenes_T$Sample)
  df_log2_highVarGenes_T$Sample <-NULL

  #preform PCA analysis
  res.pca <-PCA(df_log2_highVarGenes_T, graph = FALSE)
  
  #print scree plot to identify elbow and contribution of components.
  scree<-fviz_eig(res.pca, addlabels = TRUE, main = paste(GENESTRUCTURE, " scree plot"))
  print(scree)
  #extract relevant information from res.pca
  str(res.pca)
  
  
  percentage<-as.data.frame(res.pca[[1]][1:3,2])
  percentage[1,1]
  
PCAFig<-
  as.data.frame(res.pca[[3]][1]) %>%
    add_rownames("sample") %>%
    separate(sample, into = c("Protein", "Timepoint", "Rep")) %>%
    ggplot() +
    geom_point(aes(x=coord.Dim.1,y=coord.Dim.2,color=Protein, shape = Rep)) + 
              geom_vline(xintercept = 0, linetype = "dashed", alpha =0.5) +
              geom_hline(yintercept = 0, linetype = "dashed", alpha =0.5) +
             stat_ellipse(aes(x=coord.Dim.1,y=coord.Dim.2,color=Protein), type="t") +
             xlab(paste0("PC1 (",round(percentage[1,1], 2),"%)")) +
             ylab(paste0("PC2 (",round(percentage[2,1], 2),"%)")) +
             labs(subtitle = paste0("PCA plot of xiCLIP most variance , ", GENESTRUCTURE,", genes (log2)"),
                  caption = paste0("mostVariation - over 100 counts\nusing PCA()\nn =",unique_genes)) + 
          theme(text = element_text(size=8)) +
      coord_cartesian(xlim=c(-170,225), ylim=c(-90,65))

print(PCAFig)  

}

```
```{r, fig.asp= 1, message = F, warning = F, tidy=T}
PCAPlot(data2, "multiExonic")


```
```{r, fig.asp= 1, message = F, warning = F, tidy=T}

PCAPlot(data2, "monoExonic")

```








