---
title: "Supplementary Fig.1 f"
author: "RAC"
date: "22/09/2022"
output:
  pdf_document: default
  html_document: default
---

```{r}
#script used 

#for f in 2_QC_mapped/CBP*DMSO*SoUmiDedupRemSec.bam ;  do  OUT=$(basename $f | sed 's/SoUmiDedupRemSec.bam//g') ; samtools view -f66 $f | cut -f9 | awk '{print sqrt($0^2)}' | awk '$0<1000' | sed 's/  /\t/g' > "3_read_length/"$OUT"readlengthlong.txt" ; done 
```
above script was used to extract insert size from mapped bamfile. Insert sizes above 1000nt were removed, as these probably were due to spliced reads. Data below shows box plots of insert size from CBP20 1-2 and CBP80 1-3
```{r fig.width=3}
library(dplyr)
library(tidyr)
library(ggplot2)

df<-read.csv("../../data/readLengthCBPlongextra.txt", sep = " ", header = F) 
colnames(df)<-c("sample","length")

fig<-
df %>% 
  separate(sample, c("protein","rep", "timepoint")) %>%
  filter(!(protein == "CBP20" & rep == "3")) %>%
  ggplot(aes(x=rep, y=length, fill = protein)) + 
  geom_boxplot(position = position_dodge2(preserve = "single"), outlier.shape = NA, width = 0.8) + 
  geom_point(stat="summary", position = position_dodge2(width = 0.8), size = 1) + 
  coord_cartesian(ylim = c(0,120)) + 
  labs(subtitle = "CBP - DMSO library insert size analysis",
       caption = "under 1000nt to remove reads mapped over splice junctions") + 
  xlab("Replicate") + 
  ylab("Read length") 
  
fig + 
  theme_bw() + 
  theme(text = element_text(size=10)) +
  xlab("") + 
  ylab("") + 
  labs(subtitle = "",
       caption = "") + 
  facet_grid(. ~ timepoint) 

  
```

