#!/bin/bash
#SBATCH --mem-per-cpu 40G
#SBATCH -c 8
#SBATCH -A xiCLIP
#SBATCH -t 24:00:00



WD="/home/racrna/xiCLIP/faststorage/Projects/xiCLIP_data/4_xiCLIP/"
cd $WD

OUTDIR="14_process_other_ALYREF_and_EJC_CLIP_data/"

mkdir -p $OUTDIR

INDIR1="1_Chen_ALYREF_iCLIP/"
INDIR2="2_Wilson_EJC_iCLIP/"

mkdir -p ${OUTDIR}${INDIR1} ${OUTDIR}${INDIR2}



#link chen data

cd ${OUTDIR}${INDIR1}

for INFQGZ in ~/xiCLIP/faststorage/Datasets/Chen_ALYREF_iCLIP/*iCLIP*gz;
do
ln -s ${INFQGZ} .
done

#link wilson data

cd ..

cd ${INDIR2}

for INFQGZ in ~/xiCLIP/faststorage/Datasets/Viphakone_et_al_TREX_iCLIP/*fastq.gz ;
do
ln -s ${INFQGZ} .
done
